### ISSUE TITLE
Http client headers support

### ISSUE THREAD

**Issue by Alexvojander** [Tinder/Scarlet#73] opened 2019-04-20 17:06 UTC
Hi
Don't works headers for okhttp3 client, that uses for scarlet config builds.
I need to add user token in headers, but nothing happens
It's also don't displays in logs.
Can you explain this issue? Thanks
ver 0.1.7

**Comment by Alexvojander** [comment] 2019-04-20 17:56
I think issue in this class
The new request for new connection does not contains headers of httpclient


class OkHttpClientWebSocketConnectionEstablisher(
    private val okHttpClient: OkHttpClient,
    private val requestFactory: RequestFactory
) : OkHttpWebSocket.ConnectionEstablisher {

    override fun establishConnection(webSocketListener: WebSocketListener) {
        val request = requestFactory.createRequest()
        okHttpClient.newWebSocket(request, webSocketListener)
    }
}

**Comment by zhxnlai** [comment] 2019-04-20 21:35
Hi @Alexvojander, I think this is a duplicate of #6. You could add headers using an [interceptor](https://github.com/square/okhttp/wiki/Interceptors#rewriting-requests)

**Comment by zhxnlai** [comment] 2019-04-20 21:36
Duplicate of #6

**Closed** 2019-05-02 16:28 UTC
